spring:
  profiles:
    active:
      -  dog
      -  EN
      -  qa #prod statt qa
meski:
  username: yamlUserName
  password: yamlPassword
  jdbcurl: yamlUrlforDB

---
spring:
  profiles: prod
meski:
  username: yamlProdUserName
  password: yamlProdPassword
  jdbcurl: yamlProdUrlforDB


